export const GET_ALL_EVENTS_REQUEST = "GTE_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GTE_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_ERROR = "GTE_ALL_EVENTS_ERROR";

// --- event details
export const GET_EVENTS_DEATILS_REQUEST = "GTE_EVENTS_DEATILS_REQUEST";
export const GET_EVENTS_DEATILS_SUCCESS = "GTE_EVENTS_DEATILS_SUCCESS";
export const GET_EVENTS_DEATILS_ERROR = "GTE_EVENTS_DEATILS_ERROR";

// --- TICKET GROUP DETIILS
export const GET_EVENTS_GROUP_DEATILS_REQUEST =
  "GTE_EVENTS_GROUP_DEATILS_REQUEST";
export const GET_EVENTS_GROUP_DEATILS_SUCCESS =
  "GTE_EVENTS_GROUP_DEATILS_SUCCESS";
export const GET_EVENTS_GROUP_DEATILS_ERROR = "GTE_EVENTS_GROUP_DEATILS_ERROR";

// ---- create order
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
